name: test2

on: [push]

jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
      - name: 'wget'
        run: 'wget https://github.com/milvus-io/milvus/releases/download/v2.4.6/milvus-standalone-docker-compose.yml -O docker-compose.yml'      
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            6.0.x
            7.0.x
            8.0.x
      - name: Restore
        run: |
          dotnet restore ./src/HealthChecks.Milvus/HealthChecks.Milvus.csproj &&          
          dotnet restore ./test/HealthChecks.Milvus.Tests/HealthChecks.Milvus.Tests.csproj
      - name: Build
        run: |
          dotnet build --no-restore ./src/HealthChecks.Milvus/HealthChecks.Milvus.csproj &&
          dotnet build --no-restore ./test/HealthChecks.Milvus.Tests/HealthChecks.Milvus.Tests.csproj
      - name: Test
        run: >
          dotnet test
          ./test/HealthChecks.Milvus.Tests/HealthChecks.Milvus.Tests.csproj
          --no-restore
          --no-build          
          --
